import { describe, test, expect } from "bun:test";
import { resolve } from "node:path";
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { writeConfig } from "../../src/config/writer.js";
import { readConfig } from "../../src/config/reader.js";
import type { Service } from "../../src/config/schema.js";

describe("config writer", () => {
  test("roundtrip: write then read produces same services", () => {
    const services: Service[] = [
      {
        name: "api",
        path: "./backend",
        framework: "express",
        run: "npm start",
        port: 3000,
        install: "npm install",
      },
      {
        name: "web",
        path: "./frontend",
        framework: "nextjs",
        run: "npm run dev",
        build: "npm run build",
        port: 3001,
        depends_on: ["api"],
      },
    ];

    const tmpFile = join(tmpdir(), `rift-test-${Date.now()}.yml`);

    try {
      writeConfig(tmpFile, services);
      const config = readConfig(tmpFile);

      expect(config.version).toBe(1);
      expect(config.services.length).toBe(2);

      const api = config.services.find((s) => s.name === "api")!;
      expect(api.path).toBe("./backend");
      expect(api.framework).toBe("express");
      expect(api.run).toBe("npm start");
      expect(api.port).toBe(3000);

      const web = config.services.find((s) => s.name === "web")!;
      expect(web.depends_on).toEqual(["api"]);
      expect(web.build).toBe("npm run build");
    } finally {
      try { unlinkSync(tmpFile); } catch { /* ignore */ }
    }
  });

  test("written file includes header comment", () => {
    const tmpFile = join(tmpdir(), `rift-test-${Date.now()}.yml`);
    const services: Service[] = [{
      name: "app",
      path: ".",
      framework: "express",
      run: "npm start",
    }];

    try {
      writeConfig(tmpFile, services);
      const content = readFileSync(tmpFile, "utf-8");
      expect(content.startsWith("# Generated by rift")).toBe(true);
    } finally {
      try { unlinkSync(tmpFile); } catch { /* ignore */ }
    }
  });
});
