import { writeFileSync } from "node:fs";
import { stringify } from "yaml";
import type { Service, RiftConfig } from "./schema.js";

const HEADER = "# Generated by rift — https://github.com/rift-dev/rift\n# Do not store secrets here. Use environment variables for sensitive values.\n\n";

interface YamlServiceEntry {
  path: string;
  framework: string;
  run: string;
  build?: string;
  test?: string;
  install?: string;
  port?: number;
  restart?: number;
  depends_on?: string[];
  env?: Record<string, string>;
}

function servicesToKeyed(services: Service[]): Record<string, YamlServiceEntry> {
  const keyed: Record<string, YamlServiceEntry> = {};

  for (const service of services) {
    const entry: YamlServiceEntry = {
      path: service.path,
      framework: service.framework,
      run: service.run,
    };

    if (service.build) entry.build = service.build;
    if (service.test) entry.test = service.test;
    if (service.install) entry.install = service.install;
    if (service.port !== undefined) entry.port = service.port;
    if (service.restart !== undefined) entry.restart = service.restart;
    if (service.depends_on && service.depends_on.length > 0) entry.depends_on = service.depends_on;
    if (service.env && Object.keys(service.env).length > 0) entry.env = service.env;

    keyed[service.name] = entry;
  }

  return keyed;
}

export function writeConfig(filePath: string, services: Service[]): void {
  const doc = {
    version: 1,
    services: servicesToKeyed(services),
  };

  const yamlStr = stringify(doc, { lineWidth: 0 });
  writeFileSync(filePath, HEADER + yamlStr, "utf-8");
}

export function configToYaml(services: Service[]): string {
  const doc = {
    version: 1,
    services: servicesToKeyed(services),
  };

  return HEADER + stringify(doc, { lineWidth: 0 });
}
